# Render Blueprint for Falta EMS Backend
# This file defines both backend services for deployment on Render.com

services:
  # Admin API Server
  - type: web
    name: falta-ems-admin-api
    runtime: node
    repo: https://github.com/AgniswarBanerjee05/Vikram-Solar-Falta-EMS
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: |
      cd shared && npm install && cd ../admin-server && npm install
    startCommand: cd admin-server && npm start
    healthCheckPath: /health
    envVars:
      - key: FALTA_EMS_DB_PATH
        value: /data/ems.sqlite
      - key: FALTA_EMS_JWT_SECRET
        generateValue: true
      - key: ADMIN_SERVER_PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DASHBOARD_URL
        value: https://agniswarbanerjee05.github.io/Vikram-Solar-Falta-EMS
    disk:
      name: falta-ems-data
      mountPath: /data
      sizeGB: 1

  # User API Server
  - type: web
    name: falta-ems-user-api
    runtime: node
    repo: https://github.com/AgniswarBanerjee05/Vikram-Solar-Falta-EMS
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: |
      cd shared && npm install && cd ../user-server && npm install
    startCommand: cd user-server && npm start
    healthCheckPath: /health
    envVars:
      - key: FALTA_EMS_DB_PATH
        value: /data/ems.sqlite
      - key: FALTA_EMS_JWT_SECRET
        sync: false  # Set manually - must match admin server secret
      - key: USER_SERVER_PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DASHBOARD_URL
        value: https://agniswarbanerjee05.github.io/Vikram-Solar-Falta-EMS
    disk:
      name: falta-ems-data
      mountPath: /data
      sizeGB: 1
